### PR TITLE
PRs welcome?

### PR DESCRIPTION
**Pull request by hpr1999**
Whelp, I was playing around with the repo and changed some bits and pieces before asking whether PRs are welcome.
So ... if not, well, sucks to be me 😄 

I cleaned up the HTML a bit with semantic tags and also replaced the usage of `w3.css` with some very minimal css.
(which no means that technically, w3.css isn't used now.)

<details>
<summary>Result-Screenshots</summary>

image

image

</details>

### CODE REVIEW

**Comment by derconno** [comment]
Thank you for your PR! It is of course very welcome, and I like the design :) 

However, I found one issue with your new css. Because the footer has a fixed position, there is no space allocated for it in the page layout. In case of a very small viewport, this hides the footnote, with no ability to "scroll further down": 
image

My naive approach would be to add a 40px bottom margin to the footnote. Should we implement it like this, or do you have a more elegant solution?

**Comment by hpr1999** [comment]
Ahh yeah should have thought about it when I removed that.
The margin seem a little hacky but would probably be fine, although there's approimately a million other ways to do that via flexbox or grid-layouts.

**Comment by hpr1999** [comment]
Fixed with a grid-layout.

**Comment by derconno** [comment]
...and the changes are live! Thank you for your contribution :)

**Pull request merged**
